#!/bin/csh

### v2.2
###
### This script checks portmaster.log for moved ports
### and either re-installs these (default) or allows
### you to only rebase the port(s) orgin using pkg.

## INIT section (don't change)

if ($1 == "pkg") then
	set pkg=1
else
	set pkg=0

	if ! { pkg info -e portmaster } then
	   echo "ports-mgmt/portmaster not installed (required)" > /dev/stderr
	   exit 1;
	endif
else if ($1 == "help") then
	echo "Usage: $0 [pkg]"
	echo
	echo "pkg => Changes the moved ports base using pkg."
	echo
	exit
endif

if ("`grep moved portmaster.log`" == "") then
	echo "No moved ports to process, exiting!"		> /dev/stderr
	exit 1
endif

set pm=0
echo >&! $0.log

## MAIN section

foreach a ("`grep moved portmaster.log`")
	set old=`echo "$a" | cut -d ' ' -f3`;
	set old_pm=`echo $old | cut -d '/' -f2`;
	set new=`echo "$a" | cut -d ' ' -f7`;

	if ($pkg == 1) then
		pkg set -yo $old\:$new
		if ($? == 0) then
			echo "Changed origin: $old => $new";
		else
			echo "Something went wrong."		> /dev/stderr
			exit 1
		endif
	else
		portmaster -o $new $old_pm |& tee -a $0.log
		if ($? == 0) then
			echo "Port moved: $old => $new" | tee -a $0.log
		else
			echo "Something went wrong, see $0.log." > /dev/stderr
			exit 1
		endif
	endif
end

echo "Finished processing moved port(s), now refreshing port updates."
./refresh full

