#!/bin/csh

### Checks Portmaster log for moved ports and 
### then changes their origin.

## INIT section (don't change)

if ("`grep moved portmaster.log`" == "") then
	echo "No moved ports to process, exiting!"		> /dev/stderr
	exit 1
endif

set pm=0

if ($1 == "pkg") then
	set pkg=1
endif

## MAIN section

foreach a ("`grep moved portmaster.log`")
	set old=`echo "$a" | cut -d ' ' -f3`;
	set old_pm=`echo $old | cut -d '/' -f2`;
	set new=`echo "$a" | cut -d ' ' -f7`;

	if ($pkg == 1) then
		pkg set -yo $old\:$new;
	else
		portmaster -o $new $old_pm
	endif
	echo "Changed: $old => $new";
end

echo "Finished changing port origin(s), now refreshing port updates."
./refresh upfull

