#!/bin/sh

## INIT section (don't change)

WP=`dirname $0`
ME=`basename $0`
udate=`stat -f %Sa -t %Y%m%d $WP/$0.meta`

if [ `pkg info -e portmaster` ]; then
	echo "ports-mgmt/portmaster not installed (required)"	> /dev/stderr
	exit 1;
fi

if [ -n "$udate" ]; then
	ucmd="-d $udate";
fi;

if [ "$1" == "reset" -o "$1" == "clear" -o "$2" == "reset" ]; then
	> $WP/$ME-updating.log;
	if [ "$1" == "clear" ]; then exit; fi;
fi

## FUNCTIONS section

ports_fetch() {
	portsnap fetch update
}

pkg_fetch() {
	pkg update
}

log_full() {
	portmaster -L > $WP/portmaster.log &
	log_new
}

log_new() {
	pkg version -Iol\< > $WP/$ME.log
}

log_pkg() {
	pkg version -Rol\< > $WP/$ME.log
}

log_updating() {
	for a in `cat $WP/$ME.log | cut -d '-' -f1`; do
		pkg updating $ucmd $a >> $WP/$ME-updating.log;
	done
}

## MAIN section

if [ "$1" == "" -o "$1" == "reset" ]; then
	ports_fetch && log_full && log_updating
	touch $0.meta
elif [ "$1" == "update" ]; then
	log_new
elif [ "$1" == "full" ]; then
	log_full
elif [ "$1" == "pkg" ]; then
	pkg_fetch && log_pkg && log_updating
	touch $0.meta
elif [ "$1" == "help" ]; then
	echo "Usage: $0 [reset|update|upfull|clear|pkg|help] [clear]"
	echo
	echo "reset  => Clears $ME-updating.log and performs update."
	echo "update => Quickly refreshes list of currently known new ports."
	echo "full   => Fully refreshes list of currently known new ports."
	echo "clear  => Clears $ME-updating.log and exits."
	echo "           \* Can also be used as parameter."
	echo "pkg    => Performs update without Portmaster (pkg only)."
	echo "help   => Display this message."
	echo
else
	echo "Wrong parameter!"					> /dev/stderr
	echo "Usage: $0 [reset|update|full|clear|pkg|help]"	> /dev/stderr
fi

if [ "`jobs -p`!" != "!" ]; then
	echo "Warning: background job still running!"	> /dev/stderr
fi

