#!/bin/sh

## CONFIG section

# Where the script resides
WP=/root/updates

## INIT section (don't change)

if [ $(grep moved $WP/portmaster.log) ]; then
	echo Moved ports detected, please handle those first!	> /dev/stderr
	exit 1
fi

if [ "$1" == "jail" ]; then
   if [ ! "$2" ]; then
	jail=$(awk '/^.*\{/ {print $1}' /etc/jail.conf);
	if [ ! "$jail" ]; then
		echo "No jail available, exiting!"		> /dev/stderr
		exit 1
	else
		echo "No jail specified on commandline, trying to use: $jail";
	fi
   else
	jail=$1;
   fi

   if [ ! "$(jls | grep $jail)" ]; then
	echo "Jail $jail isn't running, exiting!"		> /dev/stderr
	exit 1
   fi
fi

## FUNCTIONS

build() {
	portmaster -a -x screen -x nvidia-driver -x thunderbird -x firefox -x libreoffice\
	| tee $WP/$0$1.log
}

build_jail() {
	echo "Re-starting build process within jail $jail." > $WP/$0.log
	jexec -l $jail $WP/update
}

## MAIN section

if [ $jail ]; then
	build_jail
else
	build
fi

